CREATE DATABASE IF NOT EXISTS ESTIMATE_MANAGEMENT;

USE ESTIMATE_MANAGEMENT;

CREATE TABLE USER
(
    ID       INT         NOT NULL AUTO_INCREMENT,
    EMAIL    VARCHAR(45) NOT NULL,
    USERNAME VARCHAR(45) NOT NULL UNIQUE,
    PASSWORD VARCHAR(45) NOT NULL,
    USERTYPE VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT
(
    CODE  INT         NOT NULL AUTO_INCREMENT,
    NAME  VARCHAR(45) NOT NULL,
    IMAGE VARCHAR(45),
    PRIMARY KEY (CODE)
);

CREATE TABLE OPT
(
    CODE INT         NOT NULL AUTO_INCREMENT,
    TYPE VARCHAR(45) NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE AVAILABILITY
(
    PRODUCT INT NOT NULL,
    OPT     INT NOT NULL,
    PRIMARY KEY (PRODUCT, OPT),
    CONSTRAINT AVFOR
        FOREIGN KEY (PRODUCT)
            REFERENCES PRODUCT (CODE)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT AVBY
        FOREIGN KEY (OPT)
            REFERENCES OPT (CODE)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE TABLE ESTIMATE
(
    CODE     INT NOT NULL AUTO_INCREMENT,
    PRODUCT  INT NOT NULL,
    CLIENT   INT NOT NULL,
    EMPLOYEE INT           DEFAULT NULL,
    PRICE    DOUBLE DEFAULT NULL,
    PRIMARY KEY (CODE),
    CONSTRAINT PROD
        FOREIGN KEY (PRODUCT)
            REFERENCES PRODUCT (CODE)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

CREATE TABLE DECOR
(
    ESTIMATE INT NOT NULL,
    OPT      INT NOT NULL,
    PRIMARY KEY (ESTIMATE, OPT),
    CONSTRAINT DECORATING
        FOREIGN KEY (ESTIMATE)
            REFERENCES ESTIMATE (CODE)
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT DECORATOR
        FOREIGN KEY (OPT)
            REFERENCES OPT (CODE)
            ON UPDATE CASCADE
            ON DELETE CASCADE
);


