INSERT INTO product(NAME, IMAGE) VALUES ('Knife', 'kitchen-knife_1f52a.png');
INSERT INTO product(NAME, IMAGE) VALUES ('Hammer', 'hammer_1f528.png');
INSERT INTO product(NAME, IMAGE) VALUES ('Keyboard', 'keyboard_2328-fe0f.png');
INSERT INTO product(NAME, IMAGE) VALUES ('Soap', 'soap_1f9fc.png');
INSERT INTO product(NAME, IMAGE) VALUES ('Wrench', 'wrench_1f527.png');

SELECT * FROM product;

INSERT INTO opt(NAME, TYPE) VALUES ('Long', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Medium', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Short', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Serrated', 'SALE');
INSERT INTO opt(NAME, TYPE) VALUES ('Red', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Blue', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Green', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Yellow', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Italian Layout', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('German Layout', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('France Layout', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('US Layout', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Lavender', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Cinnamon', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Rose', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('Chocolate', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('10 Imperial', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('10 Metric', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('12 Metric', 'STANDARD');
INSERT INTO opt(NAME, TYPE) VALUES ('14 Metric', 'STANDARD');

SELECT * FROM OPT;

UPDATE OPT SET TYPE = 'SALE' WHERE CODE = 7;
UPDATE OPT SET TYPE = 'SALE' WHERE CODE = 12;
UPDATE OPT SET TYPE = 'SALE' WHERE CODE = 16;
UPDATE OPT SET TYPE = 'SALE' WHERE CODE = 17;

INSERT INTO availability (PRODUCT, OPT) VALUES (1, 1);
INSERT INTO availability (PRODUCT, OPT) VALUES (1, 2);
INSERT INTO availability (PRODUCT, OPT) VALUES (1, 3);
INSERT INTO availability (PRODUCT, OPT) VALUES (1, 4);
INSERT INTO availability (PRODUCT, OPT) VALUES (1, 5);
INSERT INTO availability (PRODUCT, OPT) VALUES (1, 6);
INSERT INTO availability (PRODUCT, OPT) VALUES (1, 7);
INSERT INTO availability (PRODUCT, OPT) VALUES (1, 8);
INSERT INTO availability (PRODUCT, OPT) VALUES (2, 1);
INSERT INTO availability (PRODUCT, OPT) VALUES (2, 2);
INSERT INTO availability (PRODUCT, OPT) VALUES (2, 3);
INSERT INTO availability (PRODUCT, OPT) VALUES (2, 5);
INSERT INTO availability (PRODUCT, OPT) VALUES (2, 6);
INSERT INTO availability (PRODUCT, OPT) VALUES (2, 7);
INSERT INTO availability (PRODUCT, OPT) VALUES (3, 9);
INSERT INTO availability (PRODUCT, OPT) VALUES (3, 10);
INSERT INTO availability (PRODUCT, OPT) VALUES (3, 11);
INSERT INTO availability (PRODUCT, OPT) VALUES (3, 12);
INSERT INTO availability (PRODUCT, OPT) VALUES (3, 7);
INSERT INTO availability (PRODUCT, OPT) VALUES (3, 8);
INSERT INTO availability (PRODUCT, OPT) VALUES (4, 13);
INSERT INTO availability (PRODUCT, OPT) VALUES (4, 14);
INSERT INTO availability (PRODUCT, OPT) VALUES (4, 15);
INSERT INTO availability (PRODUCT, OPT) VALUES (4, 16);
INSERT INTO availability (PRODUCT, OPT) VALUES (5, 17);
INSERT INTO availability (PRODUCT, OPT) VALUES (5, 18);
INSERT INTO availability (PRODUCT, OPT) VALUES (5, 19);
INSERT INTO availability (PRODUCT, OPT) VALUES (5, 20);
INSERT INTO availability (PRODUCT, OPT) VALUES (5, 5);

SELECT P.NAME, O.NAME
FROM PRODUCT AS P JOIN AVAILABILITY AS A ON P.CODE = A.PRODUCT
    JOIN OPT AS O ON A.OPT = O.CODE;

INSERT INTO USER(EMAIL, USERNAME, PASSWORD, USERTYPE) VALUES('aldo84@ristorante.it', 'aldo84', 'p@ssw0rd', 'CLIENT');
INSERT INTO USER(EMAIL, USERNAME, PASSWORD, USERTYPE) VALUES('edoardo.bassini@pollimi.it', 'edobass45', 'p@ssw0rd', 'EMPLOYEE');

SELECT * FROM USER;

SELECT USERNAME FROM USER WHERE USERNAME = 'aldo84';

SELECT * FROM estimate;
SELECT * FROM decor;

SELECT E.CODE, U.USERNAME, P.NAME FROM ESTIMATE AS E JOIN PRODUCT AS P ON E.PRODUCT = P.CODE JOIN USER AS U ON E.CLIENT = U.ID;